#! /usr/bin/env python
# encoding: utf-8

# The search path is relevant for the shared library
search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

# By default, we use the static library to make debugging easier
kodoc_lib = 'kodoc_static'

# We need to use the kodoc static library on Android and iOS
#if bld.get_mkspec_platform() in ['android', 'ios']:
#    kodoc_lib = 'kodoc_static'

bld.program(
    features='cxx test',
    source=['kodoc_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='../kodoc_tests',
    rpath=search_path,
    use=[kodoc_lib, 'gtest'])
