#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='c',
            source='sparse_seed.c',
            target='../../sparse_seed',
            rpath=search_path,
            use=['kodoc'])
