#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='c',
            source='shallow_encode_decode.c',
            target='shallow_encode_decode',
            rpath=search_path,
            use=['kodoc'])
