// Copyright Steinwurf ApS 2014.
// Distributed under the "STEINWURF RESEARCH LICENSE 1.0".
// See accompanying file LICENSE.rst or
// http://www.steinwurf.com/licensing

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <kodoc/kodoc.h>

/// @example uncoded_symbols.c
///
/// Example showing how to process original symbols that were transmitted
/// without kodo headers. These symbols are inserted manually to the decoder
/// before the coded packets are processed.

int main()
{
    // Seed random number generator to produce different results every time
    srand(time(NULL));

    // Set the number of symbols (i.e. the generation size in RLNC
    // terminology) and the size of a symbol in bytes
    uint32_t symbols = 10;
    uint32_t symbol_size = 100;

    // Here we select the finite field to use.
    // Some common choices are: kodoc_binary, kodoc_binary4, kodoc_binary8
    int32_t finite_field = kodoc_binary;

    kodoc_factory_t encoder_factory = kodoc_new_encoder_factory(
        kodoc_sparse_full_vector, finite_field, symbols, symbol_size);

    kodoc_factory_t decoder_factory = kodoc_new_decoder_factory(
        kodoc_full_vector, finite_field, symbols, symbol_size);

    kodoc_coder_t encoder = kodoc_factory_build_coder(encoder_factory);
    kodoc_coder_t decoder = kodoc_factory_build_coder(decoder_factory);

    // In this example, we do not use systematic coding. The original symbols
    // will be transferred to the decoder without using kodo.
    //
    // We explicitly turn off the systematic mode on the encoder:
    if (kodoc_has_systematic_interface(encoder))
    {
        kodoc_set_systematic_off(encoder);
    }
    printf("Systematic encoding disabled\n");

    // Set the coding vector density on the encoder
    kodoc_set_density(encoder, 0.2);
    printf("Coding vector density: %3.2f\n", kodoc_density(encoder));

    uint32_t bytes_used;
    uint32_t payload_size = kodoc_payload_size(encoder);
    uint8_t* payload = (uint8_t*) malloc(payload_size);

    // Allocate symbols in non-contiguous buffers
    uint8_t** input_symbols = (uint8_t**) malloc(symbols * sizeof(uint8_t*));
    uint8_t** output_symbols = (uint8_t**) malloc(symbols * sizeof(uint8_t*));

    uint32_t i, j;
    // Create the original symbols and store them in the encoder
    for (i = 0; i < symbols; ++i)
    {
        // Create the individual symbols for the encoder
        input_symbols[i] = (uint8_t*) malloc(symbol_size);

        // Randomize input data
        for (j = 0; j < symbol_size; ++j)
            input_symbols[i][j] = rand() % 256;

        // Store the symbol pointer in the encoder
        kodoc_set_const_symbol(encoder, i, input_symbols[i], symbol_size);
    }

    // Transfer the original symbols to the decoder with some losses
    uint32_t lost_payloads = 0;
    for (i = 0; i < symbols; ++i)
    {
        // Create the output symbol buffers for the decoder
        output_symbols[i] = (uint8_t*) malloc(symbol_size);

        // Specify the output buffers used for decoding
        kodoc_set_mutable_symbol(decoder, i, output_symbols[i], symbol_size);

        // Simulate a channel with a 50% loss rate
        if (rand() % 2)
        {
            lost_payloads++;
            printf("Symbol %d lost on channel\n\n", i);
            continue;
        }

        // If the symbol was not lost, then insert that symbol into the decoder
        // using the raw symbol data (no additional headers are needed)
        // This will copy the data from input_symbols[i] to output_symbols[i]
        kodoc_read_uncoded_symbol(decoder, input_symbols[i], i);
    }

    printf("Number of lost payloads: %d\n", lost_payloads);

    // Now we generate coded packets with the encoder in order to recover the
    // lost packets on the decoder side
    while (!kodoc_is_complete(decoder))
    {
        // The encoder will use a certain amount of bytes of the payload
        // buffer. It will never use more than payload_size, but it might
        // use less.
        bytes_used = kodoc_write_payload(encoder, payload);
        printf("Payload generated by encoder, rank = %d, bytes used = %d\n",
               kodoc_rank(encoder), bytes_used);

        // Pass the coded packet to the decoder
        kodoc_read_payload(decoder, payload);
        printf("Payload processed by decoder, current rank = %d\n\n",
               kodoc_rank(decoder));
    }

    // Compare the input and output symbols one-by-one
    uint32_t failures = 0;
    for (i = 0; i < symbols; ++i)
    {
        if (memcmp(input_symbols[i], output_symbols[i], symbol_size) != 0)
        {
            printf("Error: Symbol %d was not decoded correctly\n", i);
            failures++;
        }

        free(input_symbols[i]);
        free(output_symbols[i]);
    }

    if (failures == 0)
    {
        printf("Data decoded correctly\n");
    }

    free(input_symbols);
    free(output_symbols);
    free(payload);

    kodoc_delete_coder(encoder);
    kodoc_delete_coder(decoder);

    kodoc_delete_factory(encoder_factory);
    kodoc_delete_factory(decoder_factory);

    return 0;
}
