#! /usr/bin/env python
# encoding: utf-8

static_libs = []

# The C++ standard library must be added on Linux and Android
if bld.get_mkspec_platform() in ['linux', 'android']:
    static_libs = ['stdc++']

bld.program(features='c',
            source='use_trace_layers.c',
            target='use_trace_layers',
            lib=static_libs,
            use=['ckodo_static'])
