// Copyright Steinwurf ApS 2014.
// Distributed under the "STEINWURF RESEARCH LICENSE 1.0".
// See accompanying file LICENSE.rst or
// http://www.steinwurf.com/licensing

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <kodoc/kodoc.h>

/// @example encode_decode_on_the_fly.c
///
/// This example shows how to use a storage aware encoder which will
/// allow you to encode from a block before all symbols have been
/// specified. This can be useful in cases where the symbols that
/// should be encoded are produced on-the-fly. The decoder will also
/// allow you to detect whether the symbols have been partially decoded.

int main()
{
    // Seed random number generator to produce different results every time
    srand(time(NULL));

    // Set the number of symbols (i.e. the generation size in RLNC
    // terminology) and the size of a symbol in bytes
    uint32_t max_symbols = 10;
    uint32_t max_symbol_size = 100;
    // Here we select the codec we wish to use
    int32_t codec = kodoc_on_the_fly;

    // Here we select the finite field to use.
    // Some common choices are: kodoc_binary, kodoc_binary4, kodoc_binary8
    int32_t finite_field = kodoc_binary8;

    kodoc_factory_t encoder_factory = kodoc_new_encoder_factory(codec,
        finite_field, max_symbols, max_symbol_size);

    kodoc_factory_t decoder_factory = kodoc_new_decoder_factory(codec,
        finite_field, max_symbols, max_symbol_size);

    kodoc_coder_t encoder = kodoc_factory_build_coder(encoder_factory);
    kodoc_coder_t decoder = kodoc_factory_build_coder(decoder_factory);

    uint32_t payload_size = kodoc_payload_size(encoder);
    uint8_t* payload = (uint8_t*)malloc(payload_size);

    uint32_t block_size = kodoc_block_size(encoder);
    uint8_t* data_in = (uint8_t*)malloc(block_size);
    uint8_t* data_out = (uint8_t*)malloc(block_size);

    kodoc_set_mutable_symbols(decoder, data_out, block_size);

    // Keeps track of which symbols have been decoded
    uint8_t* decoded = (uint8_t*)malloc(sizeof(uint8_t)*max_symbols);

    uint32_t i = 0;
    for (i = 0; i < block_size; ++i)
        data_in[i] = rand() % 256;

    // Zero initialize the decoded array
    memset(decoded, '\0', sizeof(uint8_t)*max_symbols);

    // We are starting the encoding / decoding loop without having
    // added any data to the encoder - we will add symbols on-the-fly
    while (!kodoc_is_complete(decoder))
    {
        uint32_t bytes_used;
        // Randomly choose to add a new symbol (with 50% probability)
        // if the encoder rank is less than the maximum number of symbols
        if ((rand() % 2) && kodoc_rank(encoder) < kodoc_symbols(encoder))
        {
            // The rank of an encoder indicates how many symbols have been added,
            // i.e. how many symbols are available for encoding
            uint32_t rank = kodoc_rank(encoder);

            // Calculate the offset to the next symbol to insert
            uint8_t* symbol = data_in + (rank * kodoc_symbol_size(encoder));
            kodoc_set_const_symbol(encoder, rank, symbol,
                kodoc_symbol_size(encoder));
        }

        bytes_used = kodoc_write_payload(encoder, payload);
        printf("Payload generated by encoder, rank = %d, bytes used = %d\n",
               kodoc_rank(encoder), bytes_used);

        // Send the data to the decoders, here we just for fun
        // simulate that we are loosing 50% of the packets
        if (rand() % 2)
        {
            printf("Packet dropped\n");
            continue;
        }

        // Packet got through - pass that packet to the decoder
        kodoc_read_payload(decoder, payload);

        // The rank of a decoder indicates how many symbols have been
        // decoded or partially decoded
        printf("Payload processed by decoder, current rank = %d\n",
               kodoc_rank(decoder));

        // Check the decoder whether it is partially complete
        // For on-the-fly decoding the decoder has to support the partial
        // decoding tracker.

        if (kodoc_has_partial_decoding_interface(decoder) &&
            kodoc_is_partially_complete(decoder))
        {
            uint32_t i = 0;
            for (; i < kodoc_symbols(decoder); ++i)
            {
                if (!decoded[i] && kodoc_is_symbol_uncoded(decoder, i))
                {
                    uint32_t size = kodoc_symbol_size(encoder);
                    uint8_t* original = data_in + i * size;
                    uint8_t* target = data_out + i * size;

                    // Update that this symbol now has been decoded
                    printf("Symbol %d was decoded\n", i);
                    decoded[i] = 1;

                    // Verify the symbol against the original data
                    if (memcmp(original, target, size) == 0)
                    {
                        printf("Symbol %d decoded correctly\n", i);
                    }
                    else
                    {
                        printf("SYMBOL %d DECODING FAILED.\n", i);
                    }
                }
            }
        }
    }

    if (memcmp(data_in, data_out, block_size) == 0)
    {
        printf("Data decoded correctly\n");
    }
    else
    {
        printf("Unexpected failure to decode, please file a bug report :)\n");
    }

    free(data_in);
    free(data_out);
    free(payload);

    kodoc_delete_coder(encoder);
    kodoc_delete_coder(decoder);

    kodoc_delete_factory(encoder_factory);
    kodoc_delete_factory(decoder_factory);

    return 0;
}
