/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_steinwurf_dummy_android_MainActivity */

#ifndef _Included_com_steinwurf_dummy_android_MainActivity
#define _Included_com_steinwurf_dummy_android_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_steinwurf_dummy_android_MainActivity
 * Method:    runKodo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_steinwurf_dummy_1android_MainActivity_runKodo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
