#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

static_libs = []

if bld.is_mkspec_platform('windows'):
    static_libs = ['Ws2_32']


bld.program(features='c',
            source='udp_sender.c',
            target='../../udp_sender',
            lib=static_libs,
            rpath=search_path,
            use=['kodoc'])

bld.program(features='c',
            source='udp_receiver.c',
            target='../../udp_receiver',
            lib=static_libs,
            rpath=search_path,
            use=['kodoc'])
