#! /usr/bin/env python
# encoding: utf-8

static_libs = []

# The C++ standard library must be added on Linux and Android
if bld.get_mkspec_platform() in ['linux', 'android']:
    static_libs = ['stdc++']

if bld.is_mkspec_platform('windows'):
    static_libs = ['Ws2_32']


bld.program(features='c',
            source='udp_sender.c',
            target='udp_sender',
            lib=static_libs,
            use=['ckodo_static'])

bld.program(features='c',
            source='udp_receiver.c',
            target='udp_receiver',
            lib=static_libs,
            use=['ckodo_static'])
