// Copyright Steinwurf ApS 2015.
// Distributed under the "STEINWURF RESEARCH LICENSE 1.0".
// See accompanying file LICENSE.rst or
// http://www.steinwurf.com/licensing

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <kodoc/kodoc.h>

/// @example reed_solomon.c
///
/// Simple example showing how to encode and decode a block
/// of memory using a Reed-Solomon codec.

void trace_callback(const char* zone, const char* data, void* context)
{
    (void) context;

    if (strcmp(zone, "decoder_state") == 0)
    {
        printf("%s:\n", zone);
        printf("%s\n", data);
    }
}

int main()
{
    // Seed the random number generator to produce different results every time
    srand(time(NULL));

    // Set the number of symbols and the symbol size
    uint32_t max_symbols = 10;
    uint32_t max_symbol_size = 100;

    // Here we select the coding code_type we wish to use
    int32_t code_type = kodo_reed_solomon;

    // Here we select the finite field to use.
    // For the Reed-Solomon codec, we need to choose kodo_binary8
    int32_t finite_field = kodo_binary8;

    kodo_factory_t encoder_factory =
        kodo_new_encoder_factory(code_type, finite_field,
                                 max_symbols, max_symbol_size);

    kodo_factory_t decoder_factory =
        kodo_new_decoder_factory(code_type, finite_field,
                                 max_symbols, max_symbol_size);

    kodo_coder_t encoder = kodo_factory_build_coder(encoder_factory);
    kodo_coder_t decoder = kodo_factory_build_coder(decoder_factory);

    // Allocate some storage for a "payload". The payload is what we would
    // eventually send over a network.
    uint32_t bytes_used;
    uint32_t payload_size = kodo_payload_size(encoder);
    uint8_t* payload = (uint8_t*) malloc(payload_size);

    // Allocate input and output data buffers
    uint32_t block_size = kodo_block_size(encoder);
    uint8_t* data_in = (uint8_t*) malloc(block_size);
    uint8_t* data_out = (uint8_t*) malloc(block_size);

    // Fill the input buffer with random data
    uint32_t i = 0;
    for(; i < block_size; ++i)
        data_in[i] = rand() % 256;

    // Assign the data buffers to the encoder and decoder
    kodo_set_const_symbols(encoder, data_in, block_size);
    kodo_set_mutable_symbols(decoder, data_out, block_size);

    // Install a custom trace function for the decoder
    kodo_set_trace_callback(decoder, trace_callback, NULL);

    uint32_t lost_symbols = 0;
    uint32_t received_symbols = 0;
    while (!kodo_is_complete(decoder))
    {
        // The encoder will use a certain amount of bytes of the payload buffer
        bytes_used = kodo_write_payload(encoder, payload);
        printf("Payload generated by encoder, bytes used = %d\n", bytes_used);

        // Simulate a channel with a 50% loss rate
        if (rand() % 2)
        {
            lost_symbols++;
            printf("Symbol lost on channel\n\n");
            continue;
        }

        // Pass the generated packet to the decoder
        received_symbols++;
        kodo_read_payload(decoder, payload);
        printf("Payload processed by decoder, current rank = %d\n\n",
               kodo_rank(decoder));
    }

    printf("Number of lost symbols: %d\n", lost_symbols);
    printf("Number of received symbols: %d\n", received_symbols);

    // Check that we properly decoded the data
    if (memcmp(data_in, data_out, block_size) == 0)
    {
        printf("Data decoded correctly\n");
    }
    else
    {
        printf("Unexpected failure to decode, please file a bug report :)\n");
    }

    // Free the allocated buffers and the kodo objects
    free(data_in);
    free(data_out);
    free(payload);

    kodo_delete_coder(encoder);
    kodo_delete_coder(decoder);

    kodo_delete_factory(encoder_factory);
    kodo_delete_factory(decoder_factory);

    return 0;
}
