#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='c',
            source='switch_systematic_on_off.c',
            target='switch_systematic_on_off',
            rpath=search_path,
            use=['kodoc'])
