#! /usr/bin/env python
# encoding: utf-8

static_libs = []
search_path = []

if bld.is_mkspec_platform('windows'):
    static_libs = []
else:
    static_libs = ['stdc++']
    search_path = ['.']

bld.program(features='c',
            source='switch_systematic_on_off.c',
            target='switch_systematic_on_off_static',
            lib=static_libs,
            use=['ckodo_static'])

if 'BUILD_CKODO_SHARED_LIBRARY' in bld.env:

    bld.program(features='c',
                source='switch_systematic_on_off.c',
                target='switch_systematic_on_off_shared',
                rpath=search_path,
                use=['ckodo_shared'])
