#! /usr/bin/env python
# encoding: utf-8

static_libs = []
search_path = []

# The C++ standard library must be added on Linux and Android
if bld.get_mkspec_platform() in ['linux', 'android']:
    static_libs = ['stdc++']

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='c',
            source='encode_decode_simple.c',
            target='encode_decode_simple',
            lib=static_libs,
            use=['ckodo_static'])

if 'BUILD_CKODO_SHARED_LIBRARY' in bld.env:

    bld.program(features='c',
                source='encode_decode_simple.c',
                target='encode_decode_simple_shared',
                rpath=search_path,
                use=['ckodo_shared'])
