#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='c',
            source='encode_decode_simple.c',
            target='encode_decode_simple',
            rpath=search_path,
            use=['kodoc'])
